hw10_project/hw10_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

hw10_project/quotes/urls.py
from django.urls import path


from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<str:author_name>', views.author_detail, name='author_detail'),
    path('quote/', views.quote, name='quote'),
    path('add-author/', views.author, name='author')
]

hw10_project/users/urls.py
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url='/users/reset-password/complete',
         ),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

hw10_project/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    create_at = models.DateTimeField(auto_now_add=True)

hw10_project/users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

hw10_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Quote, Author


class QuoteForm(ModelForm):
    quote = CharField()

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50)
    born_location = CharField(max_length=150)
    description = CharField()

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

hw10_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    email = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    password1 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        module = User
        fields = ['username', 'password']

hw10_project/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .utils import get_mongo
from .models import Tag, Quote, Author
from .forms import QuoteForm, AuthorForm


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author_detail(request, author_name):
    author = get_object_or_404(Author, fullname=author_name)
    return render(request, 'quotes/author_detail.html', context={'author': author})

@login_required
def quote(request):
    tags = Tag.objects.all()
    all_authors = Author.objects.all()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            new_quote.author = Author.objects.get(id=request.POST.get('author'))
            new_quote.save()

            return redirect(to='quotes:main')
        else:
            return render(
                request,
                'quotes/quote.html',
                {'tags': tags, 'all_authors': all_authors, 'form': form},
            )
    return render(
        request,
        'quotes/quote.html',
        {'tags': tags, 'all_authors': all_authors, 'form': QuoteForm()},
    )


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            new_author.save()
            return redirect(to='quotes:main')
        else:
            return render(
                request,
                'quotes/author.html',
                {'form': form},
            )
    return render(
        request,
        'quotes/author.html',
        {'form': AuthorForm()},
    )

hw10_project/users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='users:login')
        else:
            render(request, 'users/signup.html', context={'form': form})
    return render(request, 'users/signup.html', context={'form': RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"

hw10_project/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Adding author</h1>
<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Fullname:</strong>
            </label>
        </div>
        <div class="col mb-3">
            <div>{{ form.fullname }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Born date:</strong>
            </label>
            <div>{{ form.born_date }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Born location:</strong>
            </label>
            <div>{{ form.born_location }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Description:</strong>
            </label>
            <div>{{ form.description }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

hw10_project/quotes/templates/quotes/author_detail.html
{% extends "quotes/base.html" %} {% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

{% endblock %}

hw10_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
<div class="container">
    <div class="row header-box">
        <div class="col-md-8 pt-3 pb-3">
            <h1>
                <a href="{% url 'quotes:main' %}" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quotes:quote' %}" role="button">Add new quote </a></li>
                <li><a href="{% url 'quotes:author' %}" role="button">Add new author</a></li>
            </ul>
            {% endif %}
        </div>

        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <span>
                    Welcome <b>{{ user.username }}!</b>
                </span>
                <a href="{% url 'users:logout' %}">
                    <button type="button" class="btn btn-danger">Logout</button>
                </a>
                {% else %}
                <a href="{% url 'users:signup' %}">
                    <button type="button" class="btn btn-primary">Sign Up</button>
                </a>
                <a href="{% url 'users:login' %}">
                    <button type="button" class="btn btn-primary">Login</button>
                </a>
                {% endif %}
            </p>
        </div>
    </div>

        {% block content %} {% endblock %}

    </div>
</body>
</html>

hw10_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract%}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

            <li class="previous">
                <a class="{% if not quotes.has_previous %} disable {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>


            <li class="next">
                <a class="{% if not quotes.has_next %} disable {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>

        </ul>
        </nav>
    </div>
</div>

{% endblock %}

hw10_project/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}

{% block content %}
<h1 class="text-light mb-3"> Adding quote</h1>
<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mb-3">
            <label class="form-label text-light">
                <strong>Quote:</strong>
            </label>
            <div>{{ form.quote }}</div>
            {% if form.errors.name %}
            <span class="text-warning"><small>{{ form.errors.name }}</small></span>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text-light"><strong>Quote author:</strong></label>
        </div>
         <div class="mb-3 col">
            <select name="author">
                {% for author in all_authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="mb-3 col">
            <label class="form-label text-light"><strong>Select tags:</strong></label>
        </div>
        <div class="mb-3 col">
            <select name="tags" class="form-select" size="5">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </div>
</form>
{% endblock %}

hw10_project/users/templates/users/login.html
{% extends "quotes/base.html" %} {% block content %}

{% if messages %}
<div xmlns:users="http://www.w3.org/1999/xhtml" xmlns:users="http://www.w3.org/1999/xhtml">
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Username</label>
            <div>{{ form.username }}</div>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-xs-3">
            <label class="form-label">Password</label>
            <div>{{ form.password }}</div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

hw10_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw10_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw10_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw10_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw10_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw10_project/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}